module.exports = {
    // USER AUTH
    LOGIN_SUCCESS_MSG: "Login successfully",
    NEW_USER: "New User",
    ALREADY_EXIST_MSG: ' already exist',
    AUTHENTICATION_DENIED: 'Authentication denied!',
    SESSION_CODE_REQUIRED: 'Session code is required!',
    SESSION_CODE_EXPIRED: 'Session code is expired!',
    TOKEN_EXPIRED: 'Token has been expired!',
    ACCOUNT_WITH_EMAIL_EXIST: 'Account already exist with this email',
    ACCOUNT_NOT_EXIST: "User does not exist!",
    INVALID_CREDENTIAL: 'Invalid credential',
    INCORRECT_PASSWORD: 'Incorrect password',
    ACCOUNT_BLOCKED_MSG: 'Your account has been blocked. Please contact with administrator',
    FORGOT_EMAIL_SUCCESS: "Temporary password has been sent to your email",
    UNFOLLOW_SUCCESS: "Unfollow successfully",
    INVALID_PHONE: "Phone should be 10 digit.",
    // REQUEST RESPONSE TYPE MESSAGE
    ALREADY_EXIST: " already exist",
    ADD_SUCCESS: "add successfully!",
    UPDATE_SUCCESS: "update successfully!",
    CREATED_SUCCESS: "created successfully!",
    FETCH_SUCCESS: "fetched successfully!",
    UPDATED_SUCCESS: "updated successfully!",
    DELETED_SUCCESS: "deleted successfully!",
    LIST_SUCCESS: "list fetched successfully!",
    SEND_SUCCESS: "send successfully!",
    PHONE_CHANGED: "Phone number has been changed!",
    INCORRECT_OTP: "Incorrect OTP!",
    OTP_EXPIRED: "OTP has been expired",
    OTP_NOT_FOUND: "OTP not found, please resend OTP!",

    DEFAULT_MESSAGE: 'Something went wrong, Please try again.',
    SUCCESS_MESSAGE: 'Success',

    // PRODUCT
    OUT_OF_STOCK: 'OUT of stock!',
    EMPTY_CART: 'Your cart is empty!',
    CART_ITEM_NOT_FOUND: 'Cart item not found!',
}
